on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  aws_region: "ap-southeast-2"
  session_name: "deploy_example"

jobs:
  deploy:
    environment: prod
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.aws_region }}
          role-session-name: "${{ env.session_name }}"
      - name: Test Credentials
        run: |
          aws s3 ls